website/__init__.py
from flask import Flask
from .config import Config

def create_app():

    # App config
    app = Flask(__name__) 
    app.config.from_object(Config)

    # Import Blueprints
    from .routes.main import main_bp
    from .routes.stock import stock_bp
    from .routes.pokemon import pokemon_bp

    # Register Blueprints
    app.register_blueprint(main_bp, url_prefix="/")
    app.register_blueprint(stock_bp, url_prefix="/stock")
    app.register_blueprint(pokemon_bp, url_prefix="/pokemon")

    return app

website/routes/main.py
from flask import Blueprint, render_template, url_for

main_bp = Blueprint("main_bp", __name__)

@main_bp.route('/')
def home():
    return render_template("home.html")

website/routes/pokemon.py
from flask import Blueprint, render_template, url_for, jsonify, redirect, session, request
from ..data.typechart import typechart
import random

pokemon_bp = Blueprint("pokemon_bp", __name__)


@pokemon_bp.route('/')
def home():
    return render_template('/pokemon/pokemon.html')


@pokemon_bp.route('/typechart-quiz', methods=['GET', 'POST'])
def quiz_typechart():

    TOTAL_QUESTIONS = 5

    if 'questions' not in session:
        # If 'questions' key doesn't exist in the session, initiate a new quiz session.
        session['questions'] = random.sample(typechart, TOTAL_QUESTIONS)
        session['current_question'] = 0
        session['score'] = 0

    if request.method == "POST":
        user_answer = request.form.get('effectiveness')
        correct_answer = session['questions'][session['current_question']]['correct_answer']

        # Keep track of user's answer
        session['questions'][session['current_question']]['user_answer'] = user_answer

        if user_answer == correct_answer:
            session['score'] += 1

        session['current_question'] += 1

    if session['current_question'] < TOTAL_QUESTIONS:
        current_question = session['questions'][session['current_question']]
        return render_template('/pokemon/quiz_typechart.html',
                               current_question_number=session['current_question'] + 1, current_question=current_question,
                               total_questions=TOTAL_QUESTIONS)
    else:
        return redirect(url_for("pokemon_bp.quiz_result"))


@pokemon_bp.route('/result')
def quiz_result():
    questions = session['questions']
    score = session['score']
    return render_template('/pokemon/result.html', questions=questions, score=score)


@pokemon_bp.route('/reset', methods=['POST'])
def quiz_reset():
    session.pop('questions', None)
    session.pop('current_question', None)
    session.pop('score', None)
    return redirect(url_for('pokemon_bp.quiz_typechart'))

website/routes/stock.py
from flask import Blueprint, render_template, url_for

stock_bp = Blueprint("stock_bp", __name__)

@stock_bp.route('/')
def home():
    return "Hello Stock"

website/routes/views.py
from flask import Blueprint, render_template, url_for

views_bp = Blueprint("views", __name__)

@views_bp.route('/')
def home():
    return render_template("home.html")

website/templates/home.html
{% extends "layout/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1 class="my-4">What would you like to use?</h1>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
    <!-- <div class="col">
      <div class="card border-dark">        
        <div class="card-header">Stock</div>
        <div class="card-body text-dark">
          <h5 class="card-title">Risk Calculator</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="{{ url_for('stock_bp.home')}}" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div> -->
    <div class="col">
        <div class="card border-dark">        
          <div class="card-header">Pokemon</div>
          <div class="card-body text-dark">
            <h5 class="card-title">Type Chart Quiz Game</h5>
            <p class="card-text">Test your Pokemon type chart knowledge with this quiz game. Try to score as high as possible!</p>
            <a href="{{ url_for('pokemon_bp.quiz_typechart') }}" class="btn btn-primary">Start Game</a>
          </div>
        </div>
    </div>
  </div>
{% endblock %}

website/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"
        defer></script>
    <script src="https://kit.fontawesome.com/769be4c8af.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>{% include "layout/navbar.html" %}</header>
    <main class=" container-lg">
        {% block content %}{% endblock %}        
    </main>
    <footer></footer>
</body>
</html>

website/templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <!-- <a class="nav-link" href="{{ url_for('stock_bp.home') }}">Stock</a> -->
          <a class="nav-link" href="{{ url_for('pokemon_bp.home') }}">Pokemon</a>
        </div>
      </div>
    </div>
  </nav> 

website/templates/pokemon/pokemon.html
{% extends "layout/base.html" %}

website/templates/pokemon/quiz_typechart.html
{% extends "layout/base.html" %}

{% block title %}Type Chart Quiz Game{% endblock %}

{% block content %}

<h1 class="my-4">Type Chart Quiz Game</h1>

<p class="fs-4">Question {{ current_question_number }} of {{total_questions}}</p>

<div class="card-group mb-5">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <p class="card-title"><i class="fa-solid fa-fire" style="color: #c80000;"></i> Attack Party</p>
            <p class="card-text fs-5">{{ current_question.attack_party }}</p>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <p class="card-title"><i class="fa-solid fa-shield" style="color: #0052bd;"></i> Defense Party</p>
            <p class="card-text fs-5">{{ current_question.defense_party }}</p>
        </div>
    </div>
</div>


<form method="post" class="mb-3">
    <p class="fs-4">What's the effectiveness of the attack?</p>
    <div class="form-check row gy-2 col-md-6 px-0 mx-1">
        <input type="radio" class="btn-check" name="effectiveness" id="2x" value="2x" autocomplete="off">
        <label class="btn btn-outline-primary text-start ps-3" for="2x">2x (Super Effective)</label>
        <input type="radio" class="btn-check" name="effectiveness" id="1x" value="1x" autocomplete="off" >
        <label class="btn btn-outline-primary text-start ps-3" for="1x">1x (Effective)</label>
        <input type="radio" class="btn-check" name="effectiveness" id="0.5x" value="0.5x" autocomplete="off" >
        <label class="btn btn-outline-primary text-start ps-3" for="0.5x">0.5x (Not Very Effective)</label>
        <input type="radio" class="btn-check" name="effectiveness" id="0x" value="0x" autocomplete="off">
        <label class="btn btn-outline-primary text-start ps-3" for="0x">0x (No Effect)</label>
    </div>
    {% if current_question_number != total_questions %}
        <button type="submit" class="btn btn-primary my-3 col-md-2">Next</button>
    {% else %}
        <button type="submit" class="btn btn-primary my-3 col-md-2">Submit</button>
    {% endif %}   
    
</form>





{% endblock %} 

website/templates/pokemon/result.html
{% extends "layout/base.html" %}

{% block title %}Game Result{% endblock %}

{% block content %}

{% set score_ns = namespace() %}
{% set score_perc = score / questions|length * 100 %}
{% if score_perc < 50 %}
  {% set score_ns.text_color = "text-danger" %}
  {% set score_ns.icon = "fa-regular fa-face-sad-cry" %}
{% elif score_perc >= 80 %}
  {% set score_ns.text_color = "text-success" %}
  {% set score_ns.icon = "fa-solid fa-thumbs-up" %}
{% else %}
  {% set score_ns.text_color = "" %}
  {% set score_ns.icon = "" %}
{% endif %}

<p class="fs-3 mt-3 {{score_ns.text_color}}">
  <i class="{{score_ns.icon}}"></i> Total Score: {{score}} of {{questions | length}}
</p>


<div class="card-group">
{% set ns = namespace() %}
{% set ns.num = 0 %}
{% for question in questions %}
    {% set ns.num = ns.num + 1 %}

    <div class="card my-2">
        <div class="card-header">
            <strong>Question {{ ns.num }}:</strong> {{question.attack_party}} attacks {{question.defense_party}}
        </div>
        <div class="card-body">
          {% if question.correct_answer == question.user_answer %}
          <div class="card-text text-success">You got it right! The answer is {{question.correct_answer}}</div>
          {% elif question.user_answer is none %}
          <div class="card-text text-danger">The answer is {{question.correct_answer}}</div>
          <div class="card-text text-danger">You missed this one</div>
          {% else %}
          <div class="card-text text-danger">The answer is {{question.correct_answer}}</div>
          <div class="card-text text-danger">You answered {{question.user_answer}}</div>
          {% endif %}
          
          
        </div>
    </div>
</div>
        
        
{% endfor %}


<form action="{{url_for('pokemon_bp.quiz_reset')}}" method="post" class="mb-3">
    <button type="submit" class="btn btn-primary my-3 col-md-2">Play Again!</button>
</form>

{% endblock %}